#!/bin/bash

if [ -z "$1" ]; then
  echo
  echo "Usage: cursely_modpack <modpack_name>"
  echo
  exit 1
fi

modpack="$1"
temp_dir="/tmp/cursely_modpacks"

rm -rf "$temp_dir"
mkdir "$temp_dir"

echo
echo "Connecting to GitHub..."

wget --no-cache --no-cookies "https://raw.githubusercontent.com/Julynx/cursely/main/${modpack}.md" -O "${temp_dir}/${modpack}.md" > /dev/null 2>&1
cursely "${temp_dir}/${modpack}.md"
