#!/bin/bash

GREEN="$(tput setaf 2)"
NC="$(tput sgr0)"

# Check input arguments
if [ $# -eq 0 ]
  then
    echo ""
    echo "Usage: cursely_push_config <modpack_name>"
    echo ""
    exit 1
fi

# Clone the julynx/cursely repo to /tmp/cursely_git
echo ""
echo "${GREEN}Cloning julynx/cursely repo to /tmp/cursely_git...${NC}"
git clone https://github.com/julynx/cursely.git /tmp/cursely_git > /dev/null 2>&1
echo "Done!"
echo ""

# Create modpack config folder and copy necessary files
echo "${GREEN}Packaging modpack config...${NC}"
mkdir -p /tmp/cursely_git_aux/"$1"_config > /dev/null 2>&1
cp -r ~/.minecraft/config ~/.minecraft/resourcepacks ~/.minecraft/shaderpacks ~/.minecraft/options.txt /tmp/cursely_git_aux/"$1"_config/ > /dev/null 2>&1

# Zip the modpack config folder
cd /tmp/cursely_git_aux
zip -r "$1"_config.zip "$1"_config/ > /dev/null 2>&1

# Move modpack config archive to the temporal git folder
mv /tmp/cursely_git_aux/"$1"_config.zip /tmp/cursely_git/ > /dev/null 2>&1
cd /tmp/cursely_git
echo "Done!"
echo ""

# Add changes, commit, and push
echo "${GREEN}Pushing changes to julynx/cursely...${NC}"
git add * > /dev/null 2>&1
git commit -m 'Updated modpack config' > /dev/null 2>&1
git push
echo "Done!"
echo ""

# Clean up
echo "${GREEN}Cleaning up...${NC}"
cd /tmp
rm -rf /tmp/cursely_git > /dev/null 2>&1
rm -rf /tmp/cursely_git_aux > /dev/null 2>&1
echo "Done!"
echo ""
