#!/bin/bash

if [ -z "$1" ]; then
  echo
  echo "Usage: cursely_modpack <modpack_name>"
  echo
  exit 1
fi

modpack="$1"
temp_dir="/tmp/cursely_modpacks"

rm -rf "$temp_dir"
mkdir "$temp_dir"

echo
echo "Connecting to GitHub..."

wget --no-cache --no-cookies "https://raw.githubusercontent.com/Julynx/cursely/main/${modpack}.mods" -O "${temp_dir}/${modpack}.mods" > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo
  echo "Modpack '$1' not found."
  echo
  exit 1
fi
cursely "${temp_dir}/${modpack}.mods"
